#pragma once
// MESH_VP_SCHED (default off): the meshlet transform's kChecksAll loop (mesh_fastpath.hpp transform<>)
// software-pipelined over two vertices. Iteration j issues vertex j's loads, int->float conversions and FTRV
// first; vertex j-1's x/y * 1/w products, its z/y/x stores and its four screen outcode compares fill the FTRV
// latency; then vertex j's depth compares, the 1/w chain (w*w, FSRRA: consumed one iteration later), u/v and
// colour. Every per-vertex FP operation and operand is the original's (same FTRV, the same w*w FSRRA form,
// the same fmac order for u/v, the same colour LUT words), so the cache entries are bit-identical; the outcode
// byte's defined bits (screen bits 5..2, depth bits 1..0) are identical, the don't-care bits 7..6 differ (the
// original rotates argb bits into them; consumers mask with screen_mask/depth_mask).
//
// Registers: fr7..fr15 the same constants; fr0..fr3 vertex j's FTRV vector (then its u/v accumulators fr2/fr3);
// fr4 1/w of vertex j-1 (FSRRA in flight across the back edge); fr5/fr6 x/y of vertex j-1. The constant-block
// pointer becomes the depth-bit register after the prologue; r1 holds the screen bits; the colour word has its
// own register (%[c]: its lifetime overlaps the screen bits').
// Stores: one pre-decrementing pointer, back(j-1) z/y/x then (+56) front(j) argb/v/u, so the pointer advances
// once per vertex exactly as before. Reads: exactly the original's (the 3 words of each vertex in order, the
// two LUT words, the same PREF addresses); no read past the meshlet.
#include "mesh_fastpath.hpp"

namespace re4dc::vp {
#if defined(__sh__) && defined(RE4DC_HW_LEAN) && RE4DC_HW_LEAN
// The three bodies below are generated by port/dreamcast/tools/mesh_vp_sched.py (a list scheduler under hwsim.c's issue rules
// over the dependency graph of one iteration: every register / FPUL / T / pointer order is kept).
/* mesh_vp_sched.py: modelled steady-state span 36 cycles per vertex (seed 10 of 3000) */
#define VPS_PROLOGUE \
    "mov.l   @%[in]+,r1\n\t" \
    "mov.l   @%[in]+,r2\n\t" \
    "mov.l   @%[in]+,r3\n\t" \
    "extu.w  r1,r0\n\t" \
    "lds     r0,fpul\n\t" \
    "float   fpul,fr0\n\t" \
    "shlr16  r1\n\t" \
    "lds     r1,fpul\n\t" \
    "float   fpul,fr1\n\t" \
    "extu.w  r2,r0\n\t" \
    "lds     r0,fpul\n\t" \
    "float   fpul,fr2\n\t" \
    "fldi1   fr3\n\t" \
    VP_ASM_FTRV \
    "fcmp/gt fr3,fr14\n\t" \
    "movt    %[k]\n\t" \
    "fcmp/gt fr15,fr3\n\t" \
    "rotcl   %[k]\n\t" \
    "fmov    fr0,fr5\n\t" \
    "fmov    fr1,fr6\n\t" \
    "fmov    fr3,fr4\n\t" \
    "fmul    fr4,fr4\n\t" \
    VP_ASM_FSRRA4 \
    "mov     r2,r0\n\t" \
    "shlr16  r0\n\t" \
    "lds     r0,fpul\n\t" \
    "float   fpul,fr0\n\t" \
    "fmov    fr9,fr2\n\t" \
    "fmac    fr0,fr8,fr2\n\t" \
    "extu.w  r3,r0\n\t" \
    "lds     r0,fpul\n\t" \
    "float   fpul,fr0\n\t" \
    "fmov    fr11,fr3\n\t" \
    "fmac    fr0,fr10,fr3\n\t" \
    "shlr16  r3\n\t" \
    "extu.b  r3,r0\n\t" \
    "shll2   r0\n\t" \
    "mov.l   @(r0,%[lo]),%[c]\n\t" \
    "shlr8   r3\n\t" \
    "mov     r3,r0\n\t" \
    "shll2   r0\n\t" \
    "mov.l   @(r0,%[hi]),r2\n\t" \
    "or      r2,%[c]\n\t" \
    "and     %[andm],%[c]\n\t" \
    "or      %[orb],%[c]\n\t" \
    "mov.l   %[c],@-%[dst]\n\t" \
    "fmov.s  fr3,@-%[dst]\n\t" \
    "fmov.s  fr2,@-%[dst]\n\t" \
    "pref    @%[pf]\n\t" \
    "add     #12,%[pf]\n\t"
#define VPS_BODY \
    "mov.l   @%[in]+,r1\n\t" \
    "fmul    fr4,fr5\n\t" \
    "fldi1   fr3\n\t" \
    "fmul    fr4,fr6\n\t" \
    "extu.w  r1,r0\n\t" \
    "mov.l   @%[in]+,r2\n\t" \
    "lds     r0,fpul\n\t" \
    "shlr16  r1\n\t" \
    "float   fpul,fr0\n\t" \
    "lds     r1,fpul\n\t" \
    "float   fpul,fr1\n\t" \
    "extu.w  r2,r0\n\t" \
    "lds     r0,fpul\n\t" \
    "fcmp/gt fr5,fr7\n\t" \
    "float   fpul,fr2\n\t" \
    "mov     r2,r0\n\t" \
    "shlr16  r0\n\t" \
    "fmov.s  fr4,@-%[dst]\n\t" \
    "rotcl   r1\n\t" \
    "lds     r0,fpul\n\t" \
    VP_ASM_FTRV \
    "fmov.s  fr6,@-%[dst]\n\t" \
    "fmov.s  fr5,@-%[dst]\n\t" \
    "fcmp/gt fr12,fr5\n\t" \
    "mov.l   @%[in]+,r3\n\t" \
    "add     #56,%[dst]\n\t" \
    "rotcl   r1\n\t" \
    "fmov    fr9,fr2\n\t" \
    "fcmp/gt fr6,fr7\n\t" \
    "extu.w  r3,r0\n\t" \
    "shlr16  r3\n\t" \
    "pref    @%[pf]\n\t" \
    "fmov    fr0,fr5\n\t" \
    "float   fpul,fr0\n\t" \
    "lds     r0,fpul\n\t" \
    "extu.b  r3,r0\n\t" \
    "rotcl   r1\n\t" \
    "fmov    fr3,fr4\n\t" \
    "fcmp/gt fr13,fr6\n\t" \
    "shll2   r0\n\t" \
    "fmac    fr0,fr8,fr2\n\t" \
    "mov.l   @(r0,%[lo]),%[c]\n\t" \
    "rotcl   r1\n\t" \
    "fmul    fr4,fr4\n\t" \
    "fcmp/gt fr3,fr14\n\t" \
    "shlr8   r3\n\t" \
    "mov     r3,r0\n\t" \
    "shll2   r1\n\t" \
    VP_ASM_FSRRA4 \
    "or      %[k],r1\n\t" \
    "shll2   r0\n\t" \
    "float   fpul,fr0\n\t" \
    "movt    %[k]\n\t" \
    "mov.l   @(r0,%[hi]),r2\n\t" \
    "fcmp/gt fr15,fr3\n\t" \
    "fmov    fr11,fr3\n\t" \
    "mov.b   r1,@%[oc]\n\t" \
    "fmac    fr0,fr10,fr3\n\t" \
    "or      r2,%[c]\n\t" \
    "add     #12,%[pf]\n\t" \
    "and     %[andm],%[c]\n\t" \
    "add     #1,%[oc]\n\t" \
    "or      %[orb],%[c]\n\t" \
    "fmov    fr1,fr6\n\t" \
    "rotcl   %[k]\n\t" \
    "mov.l   %[c],@-%[dst]\n\t" \
    "fmov.s  fr3,@-%[dst]\n\t" \
    "fmov.s  fr2,@-%[dst]\n\t"
#define VPS_EPILOGUE \
    "fmul    fr4,fr5\n\t" \
    "fmov.s  fr4,@-%[dst]\n\t" \
    "fmul    fr4,fr6\n\t" \
    "fcmp/gt fr5,fr7\n\t" \
    "rotcl   r1\n\t" \
    "fcmp/gt fr12,fr5\n\t" \
    "rotcl   r1\n\t" \
    "fcmp/gt fr6,fr7\n\t" \
    "fmov.s  fr6,@-%[dst]\n\t" \
    "rotcl   r1\n\t" \
    "fcmp/gt fr13,fr6\n\t" \
    "fmov.s  fr5,@-%[dst]\n\t" \
    "rotcl   r1\n\t" \
    "shll2   r1\n\t" \
    "add     #56,%[dst]\n\t" \
    "or      %[k],r1\n\t" \
    "mov.b   r1,@%[oc]\n\t" \
    "add     #1,%[oc]\n\t"

template<unsigned Checks>
inline void transform_sched(const Vertex12* in,unsigned count,pvr_vertex_t* cache,std::uint8_t* oc,const Constants& k){
    if constexpr(Checks!=kChecksAll){transform<Checks>(in,count,cache,oc,k);return;}
    else {
    const AsmConstants& f=k.f;
    const float* kp=&f.zero;
    auto* dst=reinterpret_cast<std::uint32_t*>(cache)+7; // entry + 28
    const Vertex12* pf=in+3;
    const std::uint32_t* hi=k.lut;const std::uint32_t* lo=k.lut+256;
    const std::uint32_t andm=k.and_mask,orb=k.or_bits;
    std::uint32_t colour;
    __asm__ __volatile__(
        "fmov.s  @%[k]+,fr7\n\t" "fmov.s @%[k]+,fr8\n\t"  "fmov.s @%[k]+,fr9\n\t"
        "fmov.s  @%[k]+,fr10\n\t" "fmov.s @%[k]+,fr11\n\t" "fmov.s @%[k]+,fr12\n\t"
        "fmov.s  @%[k]+,fr13\n\t" "fmov.s @%[k]+,fr14\n\t" "fmov.s @%[k]+,fr15\n\t"
        // prologue: front(0)
        VPS_PROLOGUE
        "dt      %[count]\n\t"
        "bt      2f\n"
        "1:\n\t"
        VPS_BODY
        "dt      %[count]\n\t"
        "bf      1b\n"
        "2:\n\t"
        // epilogue: back(n-1)
        VPS_EPILOGUE
        : [in]"+r"(in),[count]"+r"(count),[dst]"+r"(dst),[oc]"+r"(oc),[pf]"+r"(pf),[k]"+r"(kp),[c]"=&r"(colour)
        : [lo]"r"(lo),[hi]"r"(hi),[andm]"r"(andm),[orb]"r"(orb),"m"(f)
        : "r0","r1","r2","r3","fpul","fr0","fr1","fr2","fr3","fr4","fr5","fr6","fr7",
          "fr8","fr9","fr10","fr11","fr12","fr13","fr14","fr15","t","memory" VP_ASM_FTRV_CLOBBER);
    }
}
#else
// Host tests, and the fdiv 1/w form (HW_LEAN=0): the original kernel.
template<unsigned Checks>
inline void transform_sched(const Vertex12* in,unsigned count,pvr_vertex_t* cache,std::uint8_t* oc,const Constants& k){
    transform<Checks>(in,count,cache,oc,k);
}
#endif
} // namespace re4dc::vp
