#!/usr/bin/env python3
"""cell_file.py: the PS2_INTERIOR_CULL cell as a disc file (dc/native/r100/interior.cell) plus the constants header.

The runtime (native_static.cpp namespace pc) keeps only the constants in code (ps2_interior_cell.inc: package room /
CRCs / bytes, near margin, house box, counts, file size); the sub-cells and portals are read from the disc file into an
r100-only heap-4 block when the r100 PS2 package opens, lent to route movies and read again after them.

File layout (little endian, 4-byte aligned; the runtime structs pc::Cell / pc::Portal):
  header 32 B: 'PCL1', room, mesh_crc, sidecar_crc, mesh_bytes, cell_count, portal_count, 0
  cells  cell_count x 28 B: lo xyz, hi xyz (float32), first portal, portal count (u16)
  portals portal_count x 24 B: axis (u32), plane, u0, u1, v0, v1 (float32)

  cell_file.py from-inc <old full .inc> <out .inc> <out .cell>   (convert a full emit .inc: the table values as written)
"""
import re, struct, sys
from pathlib import Path

MAGIC = b'PCL1'


def pack(room, mesh_crc, sidecar_crc, mesh_bytes, cells, portals):
    """cells: [(lo[3], hi[3], first, count)], portals: [(axis, plane, u0, u1, v0, v1)] -> bytes"""
    out = bytearray(MAGIC + struct.pack('<7I', room, mesh_crc, sidecar_crc, mesh_bytes, len(cells), len(portals), 0))
    for lo, hi, first, count in cells:
        out += struct.pack('<6f2H', *lo, *hi, first, count)
    for axis, plane, u0, u1, v0, v1 in portals:
        out += struct.pack('<I5f', axis, plane, u0, u1, v0, v1)
    return bytes(out)


def header_lines(comment, room, mesh_crc, sidecar_crc, mesh_bytes, near_max, outer, ncells, nportals, nbytes):
    return comment + [
        f'constexpr unsigned kPcRoom=0x{room:x}U,kPcMeshCrc=0x{mesh_crc:08x}U,kPcSidecarCrc=0x{sidecar_crc:08x}U,kPcMeshBytes={mesh_bytes}U;',
        f'constexpr float kPcNearMax={float(near_max):.1f}f;',
        'constexpr float kPcOuter[6]={' + ','.join(f'{float(x):.1f}f' for x in outer) + '}; // the house box: lo xyz, hi xyz',
        f'constexpr unsigned kPcCellCount={ncells}U,kPcPortalCount={nportals}U,kPcFileBytes={nbytes}U; // dc/native/r100/interior.cell',
    ]


def from_inc(src, out_inc, out_cell):
    t = Path(src).read_text()
    comment = [l for l in t.splitlines() if l.startswith('//')]
    m = re.search(r'kPcRoom=0x([0-9a-f]+)U,kPcMeshCrc=0x([0-9a-f]+)U,kPcSidecarCrc=0x([0-9a-f]+)U,kPcMeshBytes=(\d+)U', t)
    room, mc, sc, mb = int(m[1], 16), int(m[2], 16), int(m[3], 16), int(m[4])
    near = float(re.search(r'kPcNearMax=([-0-9.]+)f', t)[1])
    outer = [float(x) for x in re.search(r'kPcOuter\[6\]=\{([^}]*)\}', t)[1].replace('f', '').split(',')]
    cb = t[t.index('kPcCells[]'):t.index('kPcPortals[]')]
    cells = [([float(a), float(b), float(c)], [float(d), float(e), float(f)], int(g), int(h)) for a, b, c, d, e, f, g, h in
             re.findall(r'\{\{([-0-9.]+)f,([-0-9.]+)f,([-0-9.]+)f\},\{([-0-9.]+)f,([-0-9.]+)f,([-0-9.]+)f\},(\d+),(\d+)\}', cb)]
    pb = t[t.index('kPcPortals[]'):]
    portals = [(int(a), float(b), float(c), float(d), float(e), float(f)) for a, b, c, d, e, f in
               re.findall(r'\{(\d),([-0-9.]+)f,([-0-9.]+)f,([-0-9.]+)f,([-0-9.]+)f,([-0-9.]+)f\}', pb)]
    for lo, hi, first, count in cells:
        assert first + count <= len(portals) and count <= 24
    data = pack(room, mc, sc, mb, cells, portals)
    Path(out_cell).write_bytes(data)
    comment = [l for l in comment if not l.startswith('// Generated')]
    comment.insert(0, '// Generated by tools/d367/ps2world/interior/build_cell.py emit (cell_file.py); do not edit.')
    Path(out_inc).write_text('\n'.join(header_lines(comment, room, mc, sc, mb, near, outer, len(cells), len(portals), len(data))) + '\n',
                             newline='\n')
    print(f'{out_cell}: {len(cells)} cells, {len(portals)} portals, {len(data)} B')


if __name__ == '__main__':
    if len(sys.argv) == 5 and sys.argv[1] == 'from-inc':
        from_inc(*sys.argv[2:])
    else:
        sys.exit(__doc__)
