#!/usr/bin/env python3
"""pl08_pack.py (D367 native scene, 2026-10-04): the ACTOR_PL08_PACK costume package of the three pl08-only immutable
chunks (roles 0, 1, 8: pl08 BIN4, BIN10, BIN16).

  pl08_pack.py pack <leon_pl08_runtime.h> <out.re4cp> [--identity game/actor_pl08_pack_identity.inc]
  pl08_pack.py variants <package.re4cp> <out dir>      malformed variants for pl08_pack_test.cpp (private: they hold
                                                       converted meshes)

The bytes are the frozen converted arrays of leon_pl08_runtime.h (ACTOR_PL08_DIR, 99a776c3...) copied verbatim: no
model is rebuilt and no geometry changes. Layout (little endian; game/actor_pl08_pack_check.inc validates it):
  0  "RE4PL08\\0"   8 version 1   12 header bytes 256   16 total bytes   20 chunk count 3
  24 payload CRC32 (bytes 256..total)   28 payload FNV-1a   32 header CRC32 (bytes 0..255, this word zero)   36..63 zero
  64 + 64*k: role, source_info, position_count, normal_count, palette_count, triangles, stream_bytes,
             pos_off, pos_bytes, nrm_off, nrm_bytes, uv_off, uv_bytes, gx_off, w_off, 0
  256..: per chunk pos, nrm, uv, gx (stream_bytes), weights (palette_count * 16: bone[3], count, float[3]); each array
         starts on a 32-byte boundary, zero padding between.
The identity include pins every field and every array's CRC32 + FNV-1a, so only these exact bytes can publish.
"""
import re, struct, sys, zlib, os, hashlib

ROLES = (0, 1, 8)          # owner roles of leon_pl08::chunks[0..2]
HEADER, TABLE, ENTRY = 256, 64, 64


def fnv(b):
    f = 2166136261
    for x in b:
        f = ((f ^ x) * 16777619) & 0xffffffff
    return f


def crc(b):
    return zlib.crc32(b) & 0xffffffff


def parse_header(path):
    text = open(path, encoding='ascii').read()
    arrays = {}
    for m in re.finditer(r'alignas\(32\) static const unsigned char (\w+)\[\] = \{(.*?)\};', text, re.S):
        arrays[m.group(1)] = bytes(int(v) for v in m.group(2).replace('\n', '').split(',') if v.strip())
    for m in re.finditer(r'static const leon4k::Weight (\w+)\[\] = \{\n(.*?)\n\};', text, re.S):
        out = bytearray()
        for row in re.finditer(r'\{\{(\d+),(\d+),(\d+)\},(\d+),\{([^}]*)\}\}', m.group(2)):
            b0, b1, b2, n = (int(row.group(i)) for i in range(1, 5))
            vals = [float.fromhex(v.strip().rstrip('f')) for v in row.group(5).split(',')]
            out += struct.pack('<BBBB3f', b0, b1, b2, n, *vals)
        arrays[m.group(1)] = bytes(out)
    t = re.search(r'static const leon4k::Chunk chunks\[3\] = \{\n(.*?)\n\};', text, re.S).group(1)
    chunks = []
    for row in re.finditer(r'\{(\d+),(\d+),(\d+),(\d+),(\d+),(\d+),(\w+),(\w+),(\w+),(\w+),(\w+)\}', t):
        v = row.groups()
        chunks.append(dict(source_info=int(v[0]), position_count=int(v[1]), normal_count=int(v[2]), palette_count=int(v[3]),
                           triangles=int(v[4]), stream_bytes=int(v[5]), arrays=v[6:11]))
    assert len(chunks) == 3, chunks
    for c in chunks:
        pos, nrm, uv, gx, w = (arrays[n] for n in c['arrays'])
        assert len(pos) == c['position_count'] * 8 and len(nrm) == c['normal_count'] * 8, c
        assert len(gx) == c['stream_bytes'] and len(w) == c['palette_count'] * 16, c
    return arrays, chunks


def align(n):
    return (n + 31) & ~31


def build(arrays, chunks):
    blob, entries, at = bytearray(), [], HEADER
    for role, c in zip(ROLES, chunks):
        offs = []
        for name in c['arrays']:
            data = arrays[name]
            blob += bytes(align(at) - at); at = align(at)
            offs.append((at, len(data))); blob += data; at += len(data)
        entries.append((role, c, offs))
    total = align(at)
    blob += bytes(total - at)
    head = bytearray(HEADER)
    head[0:8] = b'RE4PL08\0'
    struct.pack_into('<IIII', head, 8, 1, HEADER, total, 3)
    for k, (role, c, offs) in enumerate(entries):
        (po, pb), (no, nb), (uo, ub), (go, gb), (wo, wb) = offs
        struct.pack_into('<16I', head, TABLE + ENTRY * k, role, c['source_info'], c['position_count'], c['normal_count'],
                         c['palette_count'], c['triangles'], c['stream_bytes'], po, pb, no, nb, uo, ub, go, wo, 0)
    payload = bytes(blob)
    struct.pack_into('<II', head, 24, crc(payload), fnv(payload))
    struct.pack_into('<I', head, 32, crc(bytes(head)))   # word 32 is zero while hashed
    return bytes(head) + payload, entries


def identity_include(pkg, entries, src_sha):
    lines = ['// GENERATED by tools/d367/pl08_pack.py from leon_pl08_runtime.h sha256 %s (ACTOR_PL08_PACK). Do not edit.' % src_sha,
             '// The exact identity of the pl08 costume package dc/native/pl08/leon_pl08.re4cp: every header / table field and',
             '// every array\'s CRC32 + FNV-1a. A package with any other byte is refused (the source path draws pl08).',
             'constexpr unsigned kPl08PackBytes=%uu,kPl08PackPayloadCrc=0x%08xu,kPl08PackPayloadFnv=0x%08xu;' %
             (len(pkg), struct.unpack_from('<I', pkg, 24)[0], struct.unpack_from('<I', pkg, 28)[0]),
             'constexpr Pl08PackExpect kPl08PackExpect[3]={']
    for role, c, offs in entries:
        hs = []
        for (o, n) in offs:
            d = pkg[o:o + n]; hs.append('0x%08xu,0x%08xu' % (crc(d), fnv(d)))
        lines.append('    {%uu,%uu,%uu,%uu,%uu,%uu,%uu,{%s},{%s}},' % (
            role, c['source_info'], c['position_count'], c['normal_count'], c['palette_count'], c['triangles'],
            c['stream_bytes'], ','.join('%uu,%uu' % o for o in offs), ','.join(hs)))
    lines.append('};')
    return '\n'.join(lines) + '\n'


def variants(pkg, out):
    """One file per malformed rule; 'fix' rewrites the hashes the change touches so the structural rule must refuse."""
    os.makedirs(out, exist_ok=True)
    def refix(b):
        b = bytearray(b); p = bytes(b[HEADER:])
        struct.pack_into('<II', b, 24, crc(p), fnv(p)); struct.pack_into('<I', b, 32, 0)
        struct.pack_into('<I', b, 32, crc(bytes(b[:HEADER]))); return bytes(b)
    def put(b, at, v):
        b = bytearray(b); struct.pack_into('<I', b, at, v); return bytes(b)
    cases = {'ok': pkg,
             'short': pkg[:-32],
             'long': pkg + bytes(32),
             'magic': b'RE4PL09\0' + pkg[8:],
             'version': refix(put(pkg, 8, 2)),
             'count': refix(put(pkg, 20, 2)),
             'header-crc': put(pkg, 32, struct.unpack_from('<I', pkg, 32)[0] ^ 1),
             'payload-bit': pkg[:HEADER + 100] + bytes([pkg[HEADER + 100] ^ 1]) + pkg[HEADER + 101:],
             'payload-bit-fixed': refix(pkg[:HEADER + 100] + bytes([pkg[HEADER + 100] ^ 1]) + pkg[HEADER + 101:]),
             'reserved': refix(put(pkg, 40, 7)),
             'role-swap': refix(put(put(pkg, TABLE, 8), TABLE + 2 * ENTRY, 0)),
             'count-field': refix(put(pkg, TABLE + 8, struct.unpack_from('<I', pkg, TABLE + 8)[0] - 1)),
             'offset-moved': refix(put(pkg, TABLE + 28, struct.unpack_from('<I', pkg, TABLE + 28)[0] + 32)),
             'offset-misaligned': refix(put(pkg, TABLE + 36, struct.unpack_from('<I', pkg, TABLE + 36)[0] + 4)),
             'offset-oob': refix(put(pkg, TABLE + ENTRY * 2 + 56, len(pkg))),
             'table-reserved': refix(put(pkg, TABLE + 60, 1)),
             'empty': b''}
    # A weight bone out of range with every hash recomputed (the per-array identity must still refuse it).
    wo = struct.unpack_from('<I', pkg, TABLE + 56)[0]
    b = bytearray(pkg); b[wo] = 200; cases['weight-bone-fixed'] = refix(bytes(b))
    for name, data in cases.items():
        open(os.path.join(out, name + '.re4cp'), 'wb').write(data)
    return list(cases)


def main():
    if len(sys.argv) >= 4 and sys.argv[1] == 'pack':
        src, out = sys.argv[2], sys.argv[3]
        arrays, chunks = parse_header(src)
        pkg, entries = build(arrays, chunks)
        os.makedirs(os.path.dirname(os.path.abspath(out)), exist_ok=True)
        open(out, 'wb').write(pkg)
        sha = hashlib.sha256(open(src, 'rb').read()).hexdigest()
        if '--identity' in sys.argv:
            open(sys.argv[sys.argv.index('--identity') + 1], 'w').write(identity_include(pkg, entries, sha))
        print('package %s bytes=%u sha256=%s from %s' % (out, len(pkg), hashlib.sha256(pkg).hexdigest(), sha))
        for role, c, offs in entries:
            print('  role %u info %u: %s' % (role, c['source_info'], ' '.join('%s@%u+%u' % (n, o, s) for n, (o, s) in
                                                                          zip(('pos', 'nrm', 'uv', 'gx', 'w'), offs))))
        return 0
    if len(sys.argv) == 4 and sys.argv[1] == 'variants':
        print(' '.join(variants(open(sys.argv[2], 'rb').read(), sys.argv[3])))
        return 0
    print(__doc__); return 2


if __name__ == '__main__':
    sys.exit(main())
